### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#181]
**Minor**
- [x] Make all public functions external
- [x] Should we rename `feePercentage` to `percentFee` to align with `baseFee`?
- [x] Remove unused imports
- [x] #218
- [x] introduce `delete` when setting a value to zero
- [x] #219
- [x] #220
- [x] double check consistent use of imported libraries (e.g. not using Ownable from solady and oz across different contracts)
- [x] If Clone.sol is only being used with approved strategies, there isn’t a need to check if they are contracts.
- [x] To be safe, in BaseStrategy.sol’s init, should check that _poolId != 0. If it ever did, then we could set it to 0 and then it could be reinitialized.
- [x] Create `internal virtual `functions for (for a more consistent implementation of our base strategy functions)
  - [x] `getRecipientStatus`
  - [x] `isValidAllocator` 

**Medium**
- [x] #221
- [x] minimize external function calls (e.g. set the registry address on initialization instead of always calling `Allo`)

**Major**
- [x] #217
- [ ] Pack all initialize parameter in structs and adjust type size #209 
- [ ] Check for reentrancy bugs #210 
- [x] Check all initialize functions and update to use Initializable #211 
- [ ] Check all variable visibilities and add them if needed #212 
- [ ] Verify that we don't use msg.value in a loop or recursive call #213 
- [x] revisit our (NatSPec) comments: [How to good NatSpec](https://twitter.com/spearbitdao/status/1665800702122250241?utm_source=substack&utm_medium=email) #186 
- [x] In DirectGrantSimpleStrategy.sol, I think we don’t update upcomingMilestone[recipient] until a distribution is made. But that allows us to call setMilestones() twice, which means we could allocate over 100% and allow some people to double withdraw while others are left with none. #214

**Comment by 0xZakk** [comment]
Adding a bunch from my own recent review of the contracts:

- [ ] Will the fee work for tokens that do not have 18 decimals? (i.e. I think USDC is 8 or 10? What about tokens with 0 decimals)
- [ ] Should we be transferring the fee amount, and making users pay for that gas? (as opposed to holding it in the Allo contract)
- [ ] Does using Ownable for Allo.sol with our governance create the possibility of a governance attack (where token holders vote to (i.e.) withdraw from a pool?)
- [ ] Should we rename `feePercentage` to `percentFee` to align with `baseFee`?
- [ ] Can we run some gas checks? How much gas is required to create a pool? Create a profile?
- [ ] What is the process by which we want to add and remove strategies from the approved strategies list?
- [ ] Should we revisit how we're tracking the pool size in Allo?
- [ ] Is it going to be really annoying to guess what nonces are available? Could we make this easier by using a bytes array?
- [ ] Is it possible to take over an anchor someone else created?
- [ ] In the registry, if someone changes the owner of a profile, shouldn't that generate a new anchor address

**Comment by carlbarrdahl** [comment]
It would be useful to emit RegisterRecipient event in `Allo.sol` because that way we can register a listener in the frontend and update the UI when that event emits. For example redirecting the user to a different page or updating a recipient list.

Would look something like this with wagmi:
```ts
 const unwatch = useContractEvent({
    address,
    abi,
    eventName: "RegisterRecipient",
    listener(log) {
      if (log.args.sender === address) {
        // Do something here, redirect user or update UI.
        unwatch?.()
      }
    },
  })
```

**Comment by 0xZakk** [comment]
@carlbarrdahl Thank you for posting this! As you think of more, keep them coming!

**Comment by 0xZakk** [comment]
One thing that has come up is sharing common/standard structures for the metadata. Right now, we just assume it's a hash pointing to a JSON blob on IPFS. What are we expecting people to put in that JSON? Do we want to come up with specific/standard structure(s)?

**Comment by thelostone-mc** [comment]
> One thing that has come up is sharing common/standard structures for the metadata. Right now, we just assume it's a hash pointing to a JSON blob on IPFS. What are we expecting people to put in that JSON? Do we want to come up with specific/standard structure(s)?

For pools and profile, we'll have to define a structure so that it's easy to build a common explorer for different types of rounds. 
We'll have to write up a spec for this 

> It would be useful to emit RegisterRecipient event in Allo.sol because that way we can register a listener in the frontend and update the UI when that event emits. For example redirecting the user to a different page or updating a recipient list.

Hmm it might be worth doing this for distribute , allocation and register recipient

**Comment by KurtMerbeth** [comment]
@thelostone-mc i've an idea how we could implement it in a nice way.
The more important question is if the event should live on Allo or in the Strategy contract, where it lives right now.

cc: @codenamejason  @carlbarrdahl

**Comment by carlbarrdahl** [comment]
> @thelostone-mc i've an idea how we could implement it in a nice way. The more important question is if the event should live on Allo or in the Strategy contract, where it lives right now.
> 
> cc: @codenamejason @carlbarrdahl

To me it would make sense in Allo, otherwise each strategy would need to implement and make sure it's emitted.

> Hmm it might be worth doing this for distribute , allocation and register recipient

Good point!

**Comment by thelostone-mc** [comment]
From @carlbarrdahl 

> Are there any plans to support Relayers/Paymasters for Allo and the strategies contracts?
It seems it would be useful especially with the rise of AA.
This unlocks some new capabilities such as:
- Web2 Auth (Privy, MagicLink, Biconomy etc)
- Gasless transactions
- Stripe Checkout to pay tx and/or donations essentially enabling fiat funding.
It could be a way to provide better UX for non-crypto natives.
This would require replacement of most msg.sender to _msgSender() (and same with msg.value).
Each Strategy could then choose to implement an ERC2771 pointing to a paymaster. 
The fallback in BaseStrategy would be for _msgSender() to point to msg.sender.

**Comment by carlbarrdahl** [comment]
> From @carlbarrdahl
> 
> > Are there any plans to support Relayers/Paymasters for Allo and the strategies contracts?
> > It seems it would be useful especially with the rise of AA.
> > This unlocks some new capabilities such as:
> 
> * Web2 Auth (Privy, MagicLink, Biconomy etc)
> * Gasless transactions
> * Stripe Checkout to pay tx and/or donations essentially enabling fiat funding.
>   It could be a way to provide better UX for non-crypto natives.
>   This would require replacement of most msg.sender to _msgSender() (and same with msg.value).
>   Each Strategy could then choose to implement an ERC2771 pointing to a paymaster.
>   The fallback in BaseStrategy would be for _msgSender() to point to msg.sender.

Some notes regarding this here:
https://hackmd.io/XKrawB14RIWrPUvAjB5OjA

**Comment by nfrgosselin** [comment]
FYI that we moved the relayer discussion to #276 

I'm closing this ticket as all discussions/points have been moved to other tickets / resolved
